title: Yashwanth Jayaramaiah
description: Professional Data Analyst with an ability to convert complex data into effective data insights.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
